

# Set up
```{r}
mainDir <- getwd()
outPath <- "../output/CompareSurvival/paper/"
figPath <- "../figure/CompareSurvival/paper/"
dataPath <- "../data/"
scriptPath <- "../script/"

marPath <- "../output/Microarray/paper/"
tcgaPath <- "../output/TCGA/paper/"


ifelse(!dir.exists(file.path(mainDir, outPath)), dir.create(file.path(mainDir, outPath)), FALSE)
ifelse(!dir.exists(file.path(mainDir, figPath)), dir.create(file.path(mainDir, figPath)), FALSE)
ifelse(!dir.exists(file.path(mainDir, dataPath)), dir.create(file.path(mainDir, dataPath)), FALSE)
ifelse(!dir.exists(file.path(mainDir, scriptPath)), dir.create(file.path(mainDir, scriptPath)), FALSE)

# library(ggplot2)
library(tidyverse)
library(RColorBrewer)
library(ggbeeswarm)
library(SingleCellExperiment)
library(Seurat)
library(hgu133a.db)

options(digits = 3)

equal_breaks <- function(n = nBreak, s = scalingFactor, ...){
  function(x){
    # rescaling
    d <- s * diff(range(x)) / (1+2*s)
    round( seq(min(x)+d, max(x)-d, length=n), 2)
  }
}

nBreak = 3
scalingFactor = 0.05

textSize <- 1.3

currentTheme <- theme_bw() +
  theme(
    # panel.background = element_blank()
    axis.title = element_text(size = rel(textSize)),
    axis.text = element_text(angle = 0, size = rel(textSize)),
    # strip.background = element_rect(colour = "#f0f0f0", fill = "#f0f0f0"),
    strip.text = element_text(size = rel(textSize)),
    axis.line = element_line(colour = "black", size = 0.5),
    legend.position = 'top',
    legend.title = element_text(size = rel(textSize), face = "italic"),
    legend.text = element_text(size = rel(textSize)),
    legend.key.size = unit(1, 'lines'),
    ## increase the line space
    plot.title = element_text(
      face = "bold",
      size = rel(textSize),
      hjust = 0.5
    )
  )

cols <-  c(
  brewer.pal(8, "Dark2")[-5],
  brewer.pal(10, "Paired"),
  brewer.pal(12, "Set3"),
  brewer.pal(9, "Blues")[c(8, 3, 7, 4, 6, 9, 5)],
  brewer.pal(9, "Oranges")[c(8, 3, 7, 4, 6, 9, 5)],
  brewer.pal(9, "Greens")[c(8, 3, 7, 4, 6, 9, 5)],
  brewer.pal(9, "Purples")[c(8, 3, 7, 4, 6, 9, 5)],
  brewer.pal(9, "Reds")[c(8, 3, 7, 4, 6, 9, 5)],
  brewer.pal(9, "Greys")[c(8, 3, 7, 4, 6, 9, 5)],
  brewer.pal(9, "BuGn")[c(8, 3, 7, 4, 6, 9, 5)],
  brewer.pal(9, "PuRd")[c(8, 3, 7, 4, 6, 9, 5)],
  brewer.pal(9, "BuPu")[c(8, 3, 7, 4, 6, 9, 5)],
  brewer.pal(9, "YlGn")[c(8, 3, 7, 4, 6, 9, 5)])


# source(paste0(scriptPath, "visReduction_function.R"))
source("../script/coxph_analysis.R")
source("../script/survival_plot.R")
```


# OS comparison
Read data lists for OS:
```{r}
dListTCGA_os <- readRDS(paste0(tcgaPath, "TCGA_SurvivalScoreExpr_DataList_20201214.RDS"))
dListMar_os <- readRDS(paste0(marPath, "Marisa_SurvivalScoreExpr_DataFormatList_short_20201214.RDS"))
# dListTCGA_os <- readRDS(paste0(tcgaPath, "TCGA_SurvivalScoreExpr_DataList_20201124.RDS"))
# dListMar_os <- readRDS(paste0(marPath, "Marisa_SurvivalScoreExpr_DataFormatList_short_20201124.RDS"))
```

## Score pairs

```{r}
os_scorePairs_mar <- read.csv(paste0(marPath, "Marisa_Cox_OS_2ScorePairs_significant2.csv"), 
         stringsAsFactors = F, 
         check.names = F)

os_scorePairs_tcga <- read.csv(paste0(tcgaPath, "TCGA_COAD_RUV_Cox_OS_2ScorePairs_significant.csv"), 
         stringsAsFactors = F, 
         check.names = F)

com_os_scorePairs <- intersect(os_scorePairs_tcga$VariableName, os_scorePairs_mar$VariableName)
```

Common significant score pairs: 
[1] "NK_Exh_Bulk--DDR"              
[2] "NK_Exh_Bulk--IL6_JAK_STAT3"    
[3] "CD8NK_Exh_Bulk--TGFb_Signaling"

### Plot survival
```{r}
library(gridExtra)
wide2CombLong_tcga <- dListTCGA_os$wide2CombLong
wide2CombLong_mar <- dListMar_os$wide2CombLong

selScorePair_tcga <- wide2CombLong_tcga[
  wide2CombLong_tcga$Comb_Name  %in% 
    com_os_scorePairs, ]

selScorePair_mar <- wide2CombLong_mar[
  wide2CombLong_mar$Comb_Name  %in% 
    com_os_scorePairs, ]

pdf(
  paste0(figPath, "OS_Comparison_ScorePairs.pdf"),
  height = 6.5,
  width = 12
)

# i <- "NK_Exh_Bulk--OXPHOS"
for(i in com_os_scorePairs){
  survival_pairPlots(
  data1 = selScorePair_tcga,
  data2 = selScorePair_mar,
  strataName = i,
  strataNameColumn = "Comb_Name",
  strataColumn = "Comb_2status",
  mainTitle1 = "TCGA\n",
  mainTitle2 = "Marisa\n",
  timeCol1  = "OS.time",
  eventCol1 = "OS",
  timeCol2 = "OS.time",
  eventCol2 = "OS",
  nColLegend = 1,
  confInt = F,
  ylabel1 = "OS",
  ylabel2 = "OS",
  CoxPval = " < 0.05",
  cols = cols,
  currentTheme = currentTheme
  )
}
  
dev.off()

```

### Coef plot
```{r}

cox_OS_2Comb_sig_tcga <- read.csv(
  paste0(
    tcgaPath,
    "TCGA_COAD_RUV_Cox_OS_2ScorePairs_significant.csv"
  ),
  stringsAsFactors = F,
  check.names = F
)

cox_OS_2Comb_sig_mar <- read.csv(
  paste0(
    marPath,
    "Marisa_Cox_OS_2ScorePairs_significant2.csv"
  ),
  stringsAsFactors = F,
  check.names = F
)


dd_tcga <- cox_OS_2Comb_sig_tcga[grepl("DDR|IL6_JAK_STAT3|TGFb_Signaling",
                                       cox_OS_2Comb_sig_tcga$VariableName),
                                 c("VariableName",
                                   "variable",
                                   "exp(coef)",
                                   "lower .95",
                                   "upper .95",
                                   "z",
                                   "Pr(>|z|)")]


dd_mar <- cox_OS_2Comb_sig_mar[grepl("DDR|IL6_JAK_STAT3|TGFb_Signaling",
                                       cox_OS_2Comb_sig_mar$VariableName),
                                 c("VariableName",
                                   "variable",
                                   "exp(coef)",
                                   "lower .95",
                                   "upper .95",
                                   "z",
                                   "Pr(>|z|)")]

colnames(dd_tcga) <- colnames(dd_mar) <-
  c("VariableName",
    "term",
    "estimate",
    "conf.low",
    "conf.high",
    "z",
    "p-value")


dd_tcga <- dd_tcga[order(dd_tcga$estimate), ]
dd_mar <- dd_mar[order(dd_mar$estimate), ]


p1 <- ggstatsplot::ggcoefstats(
  x = dd_tcga,
  output = "plot",
  statistic = "z",
  exponentiate = T,
  # title = "TCGA (OS)", 
  xlab = "exp(coef)",
  ylab = ""
)

p2 <- ggstatsplot::ggcoefstats(
  x = dd_mar,
  output = "plot",  
  statistic = "z",
  exponentiate = T,
  # title = "Marisa (OS)", 
  xlab = "exp(coef)",
  ylab = ""
) 


# pdf(
#   paste0(figPath, "OS_Comparison_ScorePairs_CoefPlot.pdf"),
#   height = 2.5,
#   width = 10
# )

png(
  paste0(figPath, "OS_Comparison_ScorePairs_CoefPlot.png"),
  height = 2.2,
  width = 8,
  unit = "in",
  res = 400
)

grid.arrange(p1, p2,
             ncol = 2)
dev.off()



# ggsave(
#   filename = "OS_Comparison_ScorePairs_CoefPlot.png",
#   path = figPath,
#   device = "png",
#   width = 10,
#   height = 2.5,
#   dpi = 400,
#   units = "in"
# )
```


## Extreme Score pairs

```{r}
selComb <- c(
  "Low CD8_Res_Bulk & High CD8_Exh_Bulk",
  "High CD8_Res_Bulk & Low CD8_Exh_Bulk",
  
  "Low CD4_Res_Bulk & High CD4_Exh_Bulk",
  "High CD4_Res_Bulk & Low CD4_Exh_Bulk",
  
  "Low NK_Res_Bulk & High NK_Exh_Bulk",
  "High NK_Res_Bulk & Low NK_Exh_Bulk",
  
  "Low All_Exh_Bulk & High All_Res_Bulk",
  "High All_Exh_Bulk & Low All_Res_Bulk",
  

  "High CD8_Res_Bulk & Low NK_Exh_Bulk",
  "Low CD8_Res_Bulk & High NK_Exh_Bulk",
  
  "High CD4_Res_Bulk & Low NK_Exh_Bulk",
  "Low CD4_Res_Bulk & High NK_Exh_Bulk",
  
  "High CD4_Res_Bulk & Low CD8_Exh_Bulk",
  "Low CD4_Res_Bulk & High CD8_Exh_Bulk",
  
  "High CD8_Exh_Bulk & Low NK_Res_Bulk",
  "Low CD8_Exh_Bulk & High NK_Res_Bulk",
  
  
  "High CD8_Exh_Bulk & Low NK_Exh_Bulk",
  "Low CD8_Exh_Bulk & High NK_Exh_Bulk",
  
  "High CD8_Exh_Bulk & Low CD4_Exh_Bulk",
  "Low CD8_Exh_Bulk & High CD4_Exh_Bulk",
  
  "High CD4_Exh_Bulk & Low NK_Exh_Bulk",
  "Low CD4_Exh_Bulk & High NK_Exh_Bulk",
  
  
  "High CD8_Res_Bulk & Low NK_Res_Bulk",
  "Low CD8_Res_Bulk & High NK_Res_Bulk",
  
  "High CD8_Res_Bulk & Low CD4_Res_Bulk",
  "Low CD8_Res_Bulk & High CD4_Res_Bulk",
  
  "High CD4_Res_Bulk & Low NK_Res_Bulk",
  "Low CD4_Res_Bulk & High NK_Res_Bulk", 
  

  "High CD8NK_Exh_Bulk & Low CD8NK_Res_Bulk",
  "Low CD8NK_Exh_Bulk & High CD8NK_Res_Bulk"
)

```


```{r}
timeCol <- "OS.time"
eventCol <- "OS"

covarColumns_os_mar <- c("Age", "Stage", "CMS")
covarColumns_os_tcga <- c("Age", "Stage", "CMS", "MSI_TCGAbiolink_annot")

"../output/TCGA/"

wide2CombLongMarSel <- wide2CombLong_mar[wide2CombLong_mar$Comb_2status  %in% selComb,]
wide2CombLongTCGASel <- wide2CombLong_tcga[wide2CombLong_tcga$Comb_2status  %in% selComb,]

##----- In Marisa
coxMar_OS_2Comb_Extremes <-
  coxph_multitest(
    data = wide2CombLongMarSel,
    variableNameCol = "Comb_Name",
    variableCol = "Comb_2status",
    timeCol = timeCol,
    eventCol = eventCol,
    nStrata = 2,
    returnCovarStat = F,
    covarCol = covarColumns_os_mar,
    nCores = 10
  )

coxMar_OS_2Comb_Extremes_sig <- coxMar_OS_2Comb_Extremes %>% 
  filter(`Pr(>|z|)` <= 0.05) %>% 
  data.frame(check.names = F)

write.csv(coxMar_OS_2Comb_Extremes_sig, 
          paste0(marPath, "Marisa_Cox_OS_ExtremeScorePairs_significant.csv"), 
          row.names = F)

##----- In TCGA:
coxTCGA_OS_2Comb_Extremes <-
  coxph_multitest(
    data = wide2CombLongTCGASel,
    variableNameCol = "Comb_Name",
    variableCol = "Comb_2status",
    timeCol = timeCol,
    eventCol = eventCol,
    nStrata = 2,
    returnCovarStat = F,
    covarCol = covarColumns_os_tcga,
    nCores = 10
  )

coxTCGA_OS_2Comb_Extremes_sig <- coxTCGA_OS_2Comb_Extremes %>% filter(`Pr(>|z|)` <= 0.05) %>% 
  data.frame(check.names = F)


write.csv(coxTCGA_OS_2Comb_Extremes_sig,
          paste0(tcgaPath, "TCGA_Cox_OS_ExtremeScorePairs_significant.csv"),
          row.names = F)


comExtreme <- intersect(coxTCGA_OS_2Comb_Extremes_sig$VariableName, 
          coxMar_OS_2Comb_Extremes_sig$VariableName)
# "CD8_Exh_Bulk--NK_Trm_Bulk" "NK_Trm_Bulk--NK_Exh_Bulk" 

marOnlyExtreme <- coxMar_OS_2Comb_Extremes_sig$VariableName[
  ! coxMar_OS_2Comb_Extremes_sig$VariableName %in% 
    coxTCGA_OS_2Comb_Extremes_sig$VariableName
]

tcgaOnlyExtreme <- coxTCGA_OS_2Comb_Extremes_sig$VariableName[
  ! coxTCGA_OS_2Comb_Extremes_sig$VariableName %in% 
    coxMar_OS_2Comb_Extremes_sig$VariableName
]

##---- look at the extreme values significant in any data
# sigVariableName <-
#   unique(
#     c(
#       coxMar_OS_2Comb_Extremes_sig$VariableName,
#       coxTCGA_OS_2Comb_Extremes_sig$VariableName
#     )
#   )


##----- look at the extreme scores significant in both TCGA  and Marisa

selScorePair_tcga <- wide2CombLong_tcga[
  wide2CombLong_tcga$Comb_Name %in%  comExtreme &
    wide2CombLong_tcga$Comb_2status %in%  selComb, ]


selScorePair_mar <-
  wide2CombLong_mar[
    wide2CombLong_mar$Comb_Name  %in%  comExtreme &
      wide2CombLong_mar$Comb_2status %in%  selComb,]


pdf(
  paste0(figPath, "OS_Comparison_ExtremeScorePairs_signifBoth.pdf"),
  height = 5.5,
  width = 11.5
)

for(i in unique(comExtreme)){
    survival_pairPlots(
  data1 = selScorePair_tcga,
  data2 = selScorePair_mar,
  strataName = i,
  strataNameColumn = "Comb_Name",
  strataColumn = "Comb_2status",
  mainTitle1 = "TCGA\n",
  mainTitle2 = "Marisa\n",
  timeCol1 = "OS.time",
  eventCol1 = "OS",
  timeCol2 = "OS.time",
  eventCol2 = "OS",
  nColLegend = 1,
  confInt = F,
  ylabel1 = "OS",
  ylabel2 = "OS",
  CoxPval = " < 0.05",
  cols = cols,
  currentTheme = currentTheme
  )
}

dev.off()



##----- look at the extreme scores significant only in TCGA

selScorePair_tcga <- wide2CombLong_tcga[
  wide2CombLong_tcga$Comb_Name %in%  tcgaOnlyExtreme &
    wide2CombLong_tcga$Comb_2status %in%  selComb, ]


selScorePair_mar <-
  wide2CombLong_mar[
    wide2CombLong_mar$Comb_Name  %in%  tcgaOnlyExtreme &
      wide2CombLong_mar$Comb_2status %in%  selComb,]


pdf(
  paste0(figPath, "OS_Comparison_ExtremeScorePairs_signifOnlyTCGA.pdf"),
  height = 5.5,
  width = 11.5
)

for(i in unique(tcgaOnlyExtreme)){
# for(i in unique(comExtreme)){
    survival_pairPlots(
  data1 = selScorePair_tcga,
  data2 = selScorePair_mar,
  strataName = i,
  strataNameColumn = "Comb_Name",
  strataColumn = "Comb_2status",
  mainTitle1 = "TCGA\n",
  mainTitle2 = "Marisa\n",
  timeCol1 = "OS.time",
  eventCol1 = "OS",
  timeCol2 = "OS.time",
  eventCol2 = "OS",
  nColLegend = 1,
  confInt = F,
  ylabel1 = "OS",
  ylabel2 = "OS",
  CoxPval = " < 0.05 in TCGA",
  cols = cols,
  currentTheme = currentTheme
  )
}

dev.off()



##----- look at the extreme scores significant only in Marisa

selScorePair_tcga <- wide2CombLong_tcga[
  wide2CombLong_tcga$Comb_Name %in%  marOnlyExtreme &
    wide2CombLong_tcga$Comb_2status %in%  selComb, ]


selScorePair_mar <-
  wide2CombLong_mar[
    wide2CombLong_mar$Comb_Name  %in%  marOnlyExtreme &
      wide2CombLong_mar$Comb_2status %in%  selComb,]


pdf(
  paste0(figPath, "OS_Comparison_ExtremeScorePairs_signifOnlyMarisa.pdf"),
  height = 5.5,
  width = 11.5
)

for(i in unique(marOnlyExtreme)){
    survival_pairPlots(
  data1 = selScorePair_tcga,
  data2 = selScorePair_mar,
  strataName = i,
  strataNameColumn = "Comb_Name",
  strataColumn = "Comb_2status",
  mainTitle1 = "TCGA\n",
  mainTitle2 = "Marisa\n",
  timeCol1 = "OS.time",
  eventCol1 = "OS",
  timeCol2 = "OS.time",
  eventCol2 = "OS",
  nColLegend = 1,
  confInt = F,
  ylabel1 = "OS",
  ylabel2 = "OS",
  CoxPval = " < 0.05 in Marisa",
  cols = cols,
  currentTheme = currentTheme
  )
}

dev.off()


```




# PFI and RFS
We have one PFI and two versions of RFS, here we compare the DFI from TCGA to the RFS including the stage IV samples.

```{r}
dListTCGA_pfi <- readRDS(paste0(tcgaPath, "TCGA_SurvivalPFI_ScoreExpr_DataList_20201214.RDS"))
dListMar_rfs <- readRDS(paste0(marPath, "Marisa_SurvivalRFS_ScoreExpr_DataFormatList_short_20201214.RDS"))
```

## Score pairs
```{r}
rfs_scorePairs_mar <- read.csv(paste0(marPath, "Marisa_Cox_RFS_2ScorePairs_significant.csv"), 
         stringsAsFactors = F, 
         check.names = F)

pfi_scorePairs_tcga <- read.csv(paste0(tcgaPath, "TCGA_COAD_RUV_Cox_PFI_2ScorePairs_significant.csv"), 
         stringsAsFactors = F, 
         check.names = F)

com_pfi_scorePairs <- intersect(rfs_scorePairs_mar$VariableName, pfi_scorePairs_tcga$VariableName)

## on
```

Commons: 
[1] "NK_Trm_Bulk--CD8NK_Exh_Bulk" "NK_Trm_Bulk--Epi_Thiery"    
[3] "NK_Trm_Bulk--HPX_EGF_EMT"    "NK_Trm_Bulk--Peroxisome"    
[5] "NK_Trm_Bulk--TP53_signaling" "All_Trm_Bulk--OXPHOS"       
[7] "CD8NK_Trm_Bulk--TP53_neg"    "CD8NK_Exh_Bulk--NK_Trm_Bulk"
[9] "CD8NK_Exh_Bulk--DDR"  

#### Plot survival
```{r}
library(gridExtra)
wide2CombLong_tcga <- dListTCGA_pfi$wide2CombLong
# wide2CombLong_tcga$PFI.time <- wide2CombLong_tcga$PFI.time/12

wide2CombLong_mar <- dListMar_rfs$wide2CombLong

selScorePair_tcga <- wide2CombLong_tcga[
  wide2CombLong_tcga$Comb_Name  %in% 
    com_pfi_scorePairs, ]

selScorePair_mar <- wide2CombLong_mar[
  wide2CombLong_mar$Comb_Name  %in% 
    com_pfi_scorePairs, ]

pdf(
  paste0(figPath, "PFI_RFS_Comparison_ScorePairs_signifBoth.pdf"),
  height = 6.5,
  width = 12
)

for(i in com_pfi_scorePairs){
  survival_pairPlots(
  data1 = selScorePair_tcga,
  data2 = selScorePair_mar,
  strataName = i,
  strataNameColumn = "Comb_Name",
  strataColumn = "Comb_2status",
  mainTitle1 = "TCGA\n",
  mainTitle2 = "Marisa\n",
  timeCol1  = "PFI.time",
  eventCol1 = "PFI",
  timeCol2 = "RFS.time",
  eventCol2 = "RFS",
  nColLegend = 1,
  confInt = F,
  ylabel1 = "PFI",
  ylabel2 = "RFS",
  CoxPval = " < 0.05",
  cols = cols,
  currentTheme = currentTheme
  )
}
  
dev.off()

```

### Coef plot
```{r}

cox_pfi_2Comb_sig_tcga <- read.csv(
  paste0(
    tcgaPath,
    "TCGA_COAD_RUV_Cox_PFI_2ScorePairs_significant.csv"
  ),
  stringsAsFactors = F,
  check.names = F
)

cox_rfs_2Comb_sig_mar <- read.csv(
  paste0(
    marPath,
    "Marisa_Cox_RFS_2ScorePairs_significant.csv"
  ),
  stringsAsFactors = F,
  check.names = F
)

comVariables <- intersect(cox_rfs_2Comb_sig_mar$VariableName, cox_pfi_2Comb_sig_tcga$VariableName)

dd_tcga <- cox_pfi_2Comb_sig_tcga[
  cox_pfi_2Comb_sig_tcga$VariableName %in%  comVariables,
                                 c("VariableName",
                                   "variable",
                                   "exp(coef)",
                                   "lower .95",
                                   "upper .95",
                                   "z",
                                   "Pr(>|z|)")]



dd_mar <- cox_rfs_2Comb_sig_mar[
  cox_rfs_2Comb_sig_mar$VariableName  %in%  comVariables,
                                 c("VariableName",
                                   "variable",
                                   "exp(coef)",
                                   "lower .95",
                                   "upper .95",
                                   "z",
                                   "Pr(>|z|)")]

colnames(dd_tcga) <- colnames(dd_mar) <-
  c("VariableName",
    "term",
    "estimate",
    "conf.low",
    "conf.high",
    "z",
    "p-value")

## remove reciprocal duplicated term
dd_tcga <- dd_tcga[
  ! dd_tcga$term  %in% "High CD8NK_Exh_Bulk & Low DDR", ]

dd_tcga <- dd_tcga[
  ! dd_tcga$term  %in% "Low NK_Res_Bulk & High CD8NK_Exh_Bulk", ]
# 
# ## remove reciprocal duplicated term
dd_mar <- dd_mar[
  ! dd_mar$term  %in% "High NK_Res_Bulk & Low CD8NK_Exh_Bulk", ]


dd_tcga <- dd_tcga[order(dd_tcga$estimate), ]
dd_mar <- dd_mar[order(dd_mar$estimate), ]


p1 <- ggstatsplot::ggcoefstats(
  x = dd_tcga,
  output = "plot",
  statistic = "z",
  exponentiate = T,
  # title = "TCGA (OS)", 
  xlab = "exp(coef)",
  ylab = ""
)


# rownames(dd_mar) <- dd_mar$VariableName

p2 <- ggstatsplot::ggcoefstats(
  # x = dd_mar[unique(dd_tcga$VariableName), ],
  x = dd_mar,
  output = "plot",  
  statistic = "z",
  exponentiate = T,
  # title = "Marisa (OS)", 
  xlab = "exp(coef)",
  ylab = ""
) 


png(
  # paste0(figPath, "PFI_Comparison_ScorePairs_CoefPlot_ordMarisaBasedonTCGA.png"),
  paste0(figPath, "PFI_Comparison_ScorePairs_CoefPlot.png"),
  height = 3,
  width = 8,
  unit = "in",
  res = 400
)

grid.arrange(p1, p2,
             ncol = 2)
dev.off()


# 
# 
# ## remove some of the variables:
# rmVars <- c("NK_Trm_Bulk--Peroxisome", 
#             "NK_Trm_Bulk--Epi_Thiery", 
#             "All_Trm_Bulk--OXPHOS")
# 
# dd_tcga <- dd_tcga[
#   !dd_tcga$VariableName  %in% rmVars, 
# ]
# dd_mar <- dd_mar[
#   !dd_mar$VariableName  %in% rmVars, 
# ]
# 
# dd_tcga <- dd_tcga[order(dd_tcga$estimate), ]
# dd_mar <- dd_mar[order(dd_mar$estimate), ]
# 
# 
# p1 <- ggstatsplot::ggcoefstats(
#   x = dd_tcga,
#   output = "plot",
#   statistic = "z",
#   exponentiate = T,
#   # title = "TCGA (OS)", 
#   xlab = "exp(coef)",
#   ylab = ""
# )
# 
# p2 <- ggstatsplot::ggcoefstats(
#   x = dd_mar,
#   output = "plot",  
#   statistic = "z",
#   exponentiate = T,
#   # title = "Marisa (OS)", 
#   xlab = "exp(coef)",
#   ylab = ""
# ) 
# 
# 
# # pdf(
# #   paste0(figPath, "OS_Comparison_ScorePairs_CoefPlot.pdf"),
# #   height = 2.5,
# #   width = 10
# # )
# 
# png(
#   # paste0(figPath, "PFI_Comparison_ScorePairs_CoefPlot_rmVars.png"),
#   paste0(figPath, "PFI_Comparison_ScorePairs_CoefPlot.png"),
#   height = 2,
#   width = 8,
#   unit = "in",
#   res = 400
# )
# 
# grid.arrange(p1, p2,
#              ncol = 2)
# dev.off()
```




## Extreme Score pairs

```{r}

covarColumns_rfs_mar <- c("Age", "Stage", "CMS", "MMR")
covarColumns_pfi_tcga <-  c("Age", "Stage", "CMS", "MSI_TCGAbiolink_annot")

wide2CombLongMarSel <- wide2CombLong_mar[wide2CombLong_mar$Comb_2status  %in% selComb,]
wide2CombLongTCGASel <- wide2CombLong_tcga[wide2CombLong_tcga$Comb_2status  %in% selComb,]

##----- In Marisa
timeCol <- "RFS.time"
eventCol <- "RFS"

coxMar_rfs_2Comb_Extremes <-
  coxph_multitest(
    data = wide2CombLongMarSel,
    variableNameCol = "Comb_Name",
    variableCol = "Comb_2status",
    timeCol = timeCol,
    eventCol = eventCol,
    nStrata = 2,
    returnCovarStat = F,
    covarCol = covarColumns_rfs_mar,
    nCores = 10
  )

coxMar_rfs_2Comb_Extremes_sig <- coxMar_rfs_2Comb_Extremes %>% 
  filter(`Pr(>|z|)` <= 0.05) %>% 
  data.frame(check.names = F)

write.csv(coxMar_rfs_2Comb_Extremes_sig, 
          paste0(marPath, "Marisa_Cox_RFS_ExtremeScorePairs_significant.csv"), 
          row.names = F)

##----- In TCGA:
timeCol <- "PFI.time"
eventCol <- "PFI"

coxTCGA_pfi_2Comb_Extremes <-
  coxph_multitest(
    data = wide2CombLongTCGASel,
    variableNameCol = "Comb_Name",
    variableCol = "Comb_2status",
    timeCol = timeCol,
    eventCol = eventCol,
    nStrata = 2,
    returnCovarStat = F,
    covarCol = covarColumns_pfi_tcga,
    nCores = 10
  )

coxTCGA_pfi_2Comb_Extremes_sig <- coxTCGA_pfi_2Comb_Extremes %>% filter(`Pr(>|z|)` <= 0.05) %>% 
  data.frame(check.names = F)

write.csv(coxTCGA_pfi_2Comb_Extremes_sig, 
          paste0(tcgaPath, "TCGA_Cox_PFI_ExtremeScorePairs_significant.csv"), 
          row.names = F)


comExtreme <- intersect(coxTCGA_pfi_2Comb_Extremes_sig$VariableName, 
          coxMar_rfs_2Comb_Extremes_sig$VariableName)
# "CD8_Exh_Bulk--NK_Res_Bulk" "NK_Res_Bulk--NK_Exh_Bulk" 

## nothing in Marisa only:
# marOnlyExtreme <- coxMar_rfs_2Comb_Extremes_sig$VariableName[
#   ! coxMar_rfs_2Comb_Extremes_sig$VariableName %in%
#     coxTCGA_pfi_2Comb_Extremes_sig$VariableName
# ]

tcgaOnlyExtreme <- coxTCGA_pfi_2Comb_Extremes_sig$VariableName[
  ! coxTCGA_pfi_2Comb_Extremes_sig$VariableName %in% 
    coxMar_rfs_2Comb_Extremes_sig$VariableName
]

# [1] "CD8_Res_Bulk--CD8_Exh_Bulk"     "CD4_Res_Bulk--NK_Exh_Bulk"      "CD8_Res_Bulk--NK_Exh_Bulk"     
# [4] "CD4_Res_Bulk--CD8_Exh_Bulk"     "CD4_Res_Bulk--CD4_Exh_Bulk"     "CD8NK_Exh_Bulk--CD8NK_Res_Bulk"


##----- look at the extreme scores significant in both TCGA  and Marisa

selScorePair_tcga <- wide2CombLong_tcga[
  wide2CombLong_tcga$Comb_Name %in%  comExtreme &
    wide2CombLong_tcga$Comb_2status %in%  selComb, ]


selScorePair_mar <-
  wide2CombLong_mar[
    wide2CombLong_mar$Comb_Name  %in%  comExtreme &
      wide2CombLong_mar$Comb_2status %in%  selComb,]



pdf(
  paste0(figPath, "PFI_RFS_Comparison_ExtremeScorePairs_SignifBoth.pdf"),
  height = 5.5,
  width = 11.5
)

for(i in unique(comExtreme)){
    survival_pairPlots(
  data1 = selScorePair_tcga,
  data2 = selScorePair_mar,
  strataName = i,
  strataNameColumn = "Comb_Name",
  strataColumn = "Comb_2status",
  mainTitle1 = "TCGA\n",
  mainTitle2 = "Marisa\n",
  timeCol1 = "PFI.time",
  eventCol1 = "PFI",
  timeCol2 = "RFS.time",
  eventCol2 = "RFS",
  nColLegend = 1,
  confInt = F,
  ylabel1 = "PFI",
  ylabel2 = "RFS",
  CoxPval = " < 0.05",
  cols = cols,
  currentTheme = currentTheme
  )
}

dev.off()




##----- look at the extreme scores significant in both TCGA  and Marisa

selScorePair_tcga <- wide2CombLong_tcga[
  wide2CombLong_tcga$Comb_Name %in%  tcgaOnlyExtreme &
    wide2CombLong_tcga$Comb_2status %in%  selComb, ]


selScorePair_mar <-
  wide2CombLong_mar[
    wide2CombLong_mar$Comb_Name  %in%  tcgaOnlyExtreme &
      wide2CombLong_mar$Comb_2status %in%  selComb,]



pdf(
  paste0(figPath, "PFI_RFS_Comparison_ExtremeScorePairs_SignifOnlyTCGA.pdf"),
  height = 5.5,
  width = 11.5
)

for(i in unique(tcgaOnlyExtreme)){
    survival_pairPlots(
  data1 = selScorePair_tcga,
  data2 = selScorePair_mar,
  strataName = i,
  strataNameColumn = "Comb_Name",
  strataColumn = "Comb_2status",
  mainTitle1 = "TCGA\n",
  mainTitle2 = "Marisa\n",
  timeCol1 = "PFI.time",
  eventCol1 = "PFI",
  timeCol2 = "RFS.time",
  eventCol2 = "RFS",
  nColLegend = 1,
  confInt = F,
  ylabel1 = "PFI",
  ylabel2 = "RFS",
  CoxPval = " < 0.05 in TCGA",
  cols = cols,
  currentTheme = currentTheme
  )
}

dev.off()
```







